# Exam 1a for rtAnalyst - Problem 3

**Import libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

**Import dataset**

In [3]:
enum = pd.read_excel('enum.xlsx')
enum.head()

  Họ và tên người phỏng vấn  Mã số người phỏng vấn
0           Nguyen thi thao                     11
1         Nguyen khac cuong                    148
2           Le Thi Ngoc Anh                    197
3        Tran Thi Mai Huong                    210
4             Ho le kieu mi                    215

In [4]:
df = pd.read_csv('survey_data.csv')
df.head()

,submission_date,starttime,endtime,tinh,tentinh,huyen,tenhuyen,xa,tenxa,thon,...,a005,a005a,a006,a008,a008a,a008aa,a009,a009a,z8,instanceID
0,2017-09-30 17:06:04,2017-09-30 16:06:15,2017-09-30 17:05:57,Hải Dương,Hải Dương,Huyện Kim Thành,Huyện Kim Thành,Thị trấn Phú Thái,Thị trấn Phú Thái,302931075005,...,Kinh,NaN,Tốt nghiệp cấp II,Lam ruong,Làm nông nghiệp (kể cả lâm và ngư nghiệp),NaN,Nông nghiệp,NaN,Khong co,uuid:682521d6-818c-42dd-af19-0ffbbf8826d5
1,2017-10-01 10:52:11,2017-10-01 09:42:21,2017-10-01 10:52:08,Hải Dương,Hải Dương,TP Hải Dương,TP Hải Dương,Phường Việt Hòa,Phường Việt Hòa,302881054304,...,Kinh,NaN,Tốt nghiệp cấp II,Lam thue o cong ty,Lao động không có tay nghề,NaN,Công nghiệp (Nước ngoài/Liên doanh),NaN,Khong co,uuid:375040fe-7329-4f71-8ede-50d707446e9e
2,2017-09-30 17:36:58,2017-09-30 16:42:59,2017-09-30 17:36:52,Hải Dương,Hải Dương,Huyện Kim Thành,Huyện Kim Thành,Thị trấn Phú Thái,Thị trấn Phú Thái,302931075005,...,Kinh,NaN,Tốt nghiệp cấp II,Ho tro chong buon ban nho,Người lao động cho gia đình không được trả lương,NaN,Dịch vụ/Kinh doanh (Tư nhân),NaN,Khong co,uuid:cd5de6d8-1de2-413a-8728-e3619426d3f1
3,2017-09-29 09:42:07,2017-09-29 08:43:13,2017-09-29 09:42:00,Hải Dương,Hải Dương,Huyện Thanh Hà,Huyện Thanh Hà,Thị trấn Thanh Hà,Thị trấn Thanh Hà,302941081309,...,Kinh,NaN,Tốt nghiệp cấp III,Chuyen nha,Lao động có tay nghề,NaN,Công nghiệp (Nhà nước),NaN,Khong co,uuid:31c97dd8-3d23-408f-ad0f-a9edfd99f451
4,2017-09-29 14:23:46,2017-09-29 13:39:33,2017-09-29 14:23:43,Hải Dương,Hải Dương,Huyện Thanh Hà,Huyện Thanh Hà,Xã Thanh Hồng,Xã Thanh Hồng,302941087900227,...,Kinh,NaN,Tốt nghiệp cấp II,Cong nhan,Lao động không có tay nghề,NaN,Công nghiệp (Tư nhân),NaN,Khong co,uuid:ba3a2cf2-1bd5-45de-8c31-0d1c831de3e0

**Number of interviews each enumerator has completed**

In [7]:
df['nguoipv'].value_counts()

Ho le kieu mi                   51
Pham giang hoi                  48
Nguyen khac cuong               48
Nguyen thi thanh thanh          47
Nguyen thi thao                 46
LE THI KIM LY                   45
Nguyen thi hong hiep            44
Tran phuong thao                36
Nguyen ngoc phuong mai          27
Tran Thi Mai Huong              25
Le Thi Ngoc Anh                 25
Nguyen Phuong Linh              24
Nguyen thi thuong               23
Le thi kim anh                  23
Nguyen thu ha                   22
Ha Thi Kim Quy                  22
TRAN PHUONG THAO                12
Le thi kim ly                    3
Nguyen thu hong hiep             1
Tran  Thi Mai Huong              1
Nguyen thi thanh thanh thanh     1
Pha giang hoi                    1
Nguyen thi hobg hiep             1
Trăn phuong thao                 1
Nguyen phuong linh               1
Name: nguoipv, dtype: int64

In [8]:
df['submission_date'] = pd.to_datetime(df['submission_date'])
df.head()

,submission_date,starttime,endtime,tinh,tentinh,huyen,tenhuyen,xa,tenxa,thon,...,a005,a005a,a006,a008,a008a,a008aa,a009,a009a,z8,instanceID
0,2017-09-30 17:06:04,2017-09-30 16:06:15,2017-09-30 17:05:57,Hải Dương,Hải Dương,Huyện Kim Thành,Huyện Kim Thành,Thị trấn Phú Thái,Thị trấn Phú Thái,302931075005,...,Kinh,NaN,Tốt nghiệp cấp II,Lam ruong,Làm nông nghiệp (kể cả lâm và ngư nghiệp),NaN,Nông nghiệp,NaN,Khong co,uuid:682521d6-818c-42dd-af19-0ffbbf8826d5
1,2017-10-01 10:52:11,2017-10-01 09:42:21,2017-10-01 10:52:08,Hải Dương,Hải Dương,TP Hải Dương,TP Hải Dương,Phường Việt Hòa,Phường Việt Hòa,302881054304,...,Kinh,NaN,Tốt nghiệp cấp II,Lam thue o cong ty,Lao động không có tay nghề,NaN,Công nghiệp (Nước ngoài/Liên doanh),NaN,Khong co,uuid:375040fe-7329-4f71-8ede-50d707446e9e
2,2017-09-30 17:36:58,2017-09-30 16:42:59,2017-09-30 17:36:52,Hải Dương,Hải Dương,Huyện Kim Thành,Huyện Kim Thành,Thị trấn Phú Thái,Thị trấn Phú Thái,302931075005,...,Kinh,NaN,Tốt nghiệp cấp II,Ho tro chong buon ban nho,Người lao động cho gia đình không được trả lương,NaN,Dịch vụ/Kinh doanh (Tư nhân),NaN,Khong co,uuid:cd5de6d8-1de2-413a-8728-e3619426d3f1
3,2017-09-29 09:42:07,2017-09-29 08:43:13,2017-09-29 09:42:00,Hải Dương,Hải Dương,Huyện Thanh Hà,Huyện Thanh Hà,Thị trấn Thanh Hà,Thị trấn Thanh Hà,302941081309,...,Kinh,NaN,Tốt nghiệp cấp III,Chuyen nha,Lao động có tay nghề,NaN,Công nghiệp (Nhà nước),NaN,Khong co,uuid:31c97dd8-3d23-408f-ad0f-a9edfd99f451
4,2017-09-29 14:23:46,2017-09-29 13:39:33,2017-09-29 14:23:43,Hải Dương,Hải Dương,Huyện Thanh Hà,Huyện Thanh Hà,Xã Thanh Hồng,Xã Thanh Hồng,302941087900227,...,Kinh,NaN,Tốt nghiệp cấp II,Cong nhan,Lao động không có tay nghề,NaN,Công nghiệp (Tư nhân),NaN,Khong co,uuid:ba3a2cf2-1bd5-45de-8c31-0d1c831de3e0

In [9]:
df['starttime'] = pd.to_datetime(df['starttime'])
df['endtime'] = pd.to_datetime(df['endtime'])

In [18]:
df['duration'] = df[['starttime', 'endtime']].apply(lambda x: pd.Timedelta(x['endtime'] - x['starttime']), axis = 1)

In [21]:
df['duration'] = pd.to_datetime(df['duration'])

In [24]:
df['duration'] = df['duration'].apply(lambda x: x.hour * 60 + x.minute + x.second / 60)

**Duration of each interview made by a enumerator**

In [28]:
df[['nguoipv', 'duration']].head()

              nguoipv   duration
0  Nguyen Phuong Linh  59.700000
1       Nguyen thu ha  69.783333
2   Nguyen thi thuong  53.883333
3     Le Thi Ngoc Anh  58.783333
4     Le Thi Ngoc Anh  44.166667

**Average of a interview last around 53 minutes. But the table show below there are a few interview that last for over 100 minutes or even over 1000 minutes**

In [41]:
df['duration'].mean()

52.12549019607839

In [40]:
df[['nguoipv', 'duration']].sort_values(by = 'duration', ascending = False)

                    nguoipv     duration
536    Nguyen thi hong hiep  1027.983333
185       Nguyen thi thuong   300.583333
355    Nguyen thi hong hiep   221.550000
64   Nguyen ngoc phuong mai   172.533333
360           LE THI KIM LY   149.133333
510    Nguyen thi hong hiep   131.633333
138           Nguyen thu ha    99.316667
94           Le thi kim anh    96.300000
82           Ha Thi Kim Quy    96.133333
93           Ha Thi Kim Quy    93.416667
436           Ho le kieu mi    92.750000
18           Le thi kim anh    91.400000
19       Nguyen Phuong Linh    88.516667
26   Nguyen ngoc phuong mai    88.283333
525           LE THI KIM LY    86.600000
143           Nguyen thu ha    86.000000
29       Tran Thi Mai Huong    84.983333
101      Tran Thi Mai Huong    83.950000
109       Nguyen thi thuong    81.266667
404           Ho le kieu mi    80.983333
197           Ho le kieu mi    80.800000
32           Ha Thi Kim Quy    80.700000
163         Le Thi Ngoc Anh    80.450000
98       Nguyen Phuong Linh    79.566667
71           Ha Thi Kim Quy    79.133333
67          Le Thi Ngoc Anh    79.100000
39           Le thi kim anh    78.650000
453       Nguyen khac cuong    77.866667
6            Ha Thi Kim Quy    77.533333
95            Nguyen thu ha    77.200000
..                      ...          ...
258           LE THI KIM LY    35.000000
435           Ho le kieu mi    34.966667
320           LE THI KIM LY    34.950000
262        Tran phuong thao    34.916667
506         Nguyen thi thao    34.900000
248          Pham giang hoi    34.900000
259         Nguyen thi thao    34.816667
319        TRAN PHUONG THAO    34.650000
241           Ho le kieu mi    34.650000
524        Tran phuong thao    34.533333
390        Tran phuong thao    34.433333
331         Nguyen thi thao    34.366667
371        Tran phuong thao    34.350000
214           Ho le kieu mi    34.300000
395           Ho le kieu mi    34.016667
537        Tran phuong thao    33.966667
393           LE THI KIM LY    33.933333
485           Ho le kieu mi    33.816667
199           Ho le kieu mi    33.783333
80          Le Thi Ngoc Anh    33.750000
526         Nguyen thi thao    33.550000
205  Nguyen thi thanh thanh    33.516667
269        Tran phuong thao    33.450000
493           LE THI KIM LY    33.183333
419           Ho le kieu mi    32.700000
251           Ho le kieu mi    32.416667
358           Ho le kieu mi    32.283333
533           Ho le kieu mi    31.783333
563        Tran phuong thao    31.750000
218       Nguyen khac cuong    30.250000

[578 rows x 2 columns]

**Table shows below is the result of total number of missing table of each columns. There are 3 columns with nearly and over 500 missing value**

In [39]:
df.isnull().sum()

submission_date      0
starttime            0
endtime              0
tinh                 0
tentinh              0
huyen                0
tenhuyen             0
xa                   0
tenxa                0
thon                 0
tenthon              0
khuvuc               0
idcode0              0
nguoipv              0
entry                0
a001                 0
a002                 0
a005                 0
a005a              552
a006                 0
a008                 0
a008a                0
a008aa             573
a009                 0
a009a              494
z8                   0
instanceID           0
duration             0
dtype: int64

In [42]:
df['tinh'].value_counts()

Đồng Nai     385
Hải Dương    193
Name: tinh, dtype: int64

In [44]:
df['huyen'].value_counts()

Huyện Vĩnh Cửu        68
Huyện Kim Thành       68
Huyện Cẩm Mỹ          68
Thành phố Biên Hòa    67
Huyện Thanh Hà        67
Huyện Định Quán       66
Huyện Trảng Bom       59
TP Hải Dương          58
Huyện Thống Nhất      57
Name: huyen, dtype: int64

In [45]:
df['xa'].value_counts()

Xã Liên Hòa           36
Thị trấn Vĩnh An      36
Xã Thừa Đức           35
Xã Thanh Hồng         34
Xã La Ngà             34
Phường Trũng Dũng     34
Xã Hiệp Hòa           33
Xã Long Giao          33
Thị trấn Thanh Hà     33
Thị trấn Phú Thái     32
Xã Mã Đà              32
Thị trấn Định Quán    32
Xã Bàu Hàm            32
Xã Xuân Thạnh         31
Phường Việt Hòa       29
Phường Trần Phú       29
Thị trấn Trảng Bom    27
Xã Bàu Hàm 2          26
Name: xa, dtype: int64

In [46]:
df['khuvuc'].value_counts()

Nông thôn    327
Đô thị       251
Name: khuvuc, dtype: int64