# Exam 1a for rtAnalyst

**Import libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Import dataset**

In [3]:
df = pd.read_excel('CSDL_KhachHang.xlsx')
df.head()

,STT,Tên KH,Mã KH,Ngày nhập CSDL,Thôn,Xã,Huyện,Tỉnh,Mã thôn,Mã xã,Mã huyện,Mã tỉnh,SĐT,Địa chỉ KH,Bảng Giá áp dụng
0,1,Bà Liên ( Chức,TG.095.01,2017-03-10 16:45:43,Thanh Gia,Quảng Phú,Lương Tài,Bắc Ninh,TG,9514,264,27,1.677642e+09,Thanh Gia,SH
1,2,Bà Tiến,CP.022,2017-01-23 12:38:01,Chinh Phú,Trung Chính,Lương Tài,Bắc Ninh,CP,9523,264,27,NaN,Chinh Phú,SH
2,3,Bà Tĩnh,CP.018,2017-01-23 12:38:01,Chinh Phú,Trung Chính,Lương Tài,Bắc Ninh,CP,9523,264,27,NaN,Chinh Phú,SH
3,4,Bà Trừ,CP.056,2017-01-23 12:38:01,Chinh Phú,Trung Chính,Lương Tài,Bắc Ninh,CP,9523,264,27,NaN,Chinh Phú,SH
4,5,Bùi Đức Hải,TC.127,2017-01-23 12:38:01,Trung Chinh,Trung Chính,Lương Tài,Bắc Ninh,TC,9523,264,27,NaN,Trung Chinh,SH

In [ ]:
def convertPhoneNumber(pnum):
    x = str(pnum)
    if(x[0] != '1' and x[0] != 9):

In [23]:
df['SĐT'].dropna().apply(lambda x: '0' + str(x))

0        01677642406.0
50       01697685880.0
52        0968532997.0
54        0964338169.0
57        0968943324.0
58       01666172542.0
70        0987301586.0
74       01669528366.0
79        0981798697.0
81       01688972145.0
91       01682601885.0
94       01683973343.0
98       01689217697.0
100       0967982180.0
106       0975594243.0
107      01245259868.0
109       0946086346.0
111       0945312459.0
114       0973956639.0
122     016939355465.0
137      01627709296.0
146      01663965255.0
173      01653981863.0
207      01655515792.0
208       0912600256.0
215       0915326817.0
216      01662395340.0
217       0961503688.0
376      01629759761.0
378       0979746654.0
             ...
1310     01697223706.0
1311      0974635433.0
1319      0966665358.0
1321      0965625875.0
1328      0912003091.0
1332      0917626519.0
1337      0989645848.0
1338      0989071325.0
1340     01685376816.0
1347      0946851973.0
1354      0901234313.0
1355      0972729227.0
1363      0989457871.0
1367     01692134494.0
1376     01692539035.0
1380     01666000495.0
1383      0986842552.0
1385     01683525279.0
1386     01663205932.0
1393     01277012637.0
1396     01656080087.0
1403      0969569615.0
1410     01694586123.0
1413      0972458710.0
1419      0984266598.0
1420     01685762813.0
1424     01663194371.0
1431      0971410171.0
1438     01668401646.0
1440      0988071356.0
Name: SĐT, Length: 224, dtype: object

In [21]:
df[(df['Xã'] == 'Quảng Phú')][['Mã KH','SĐT', 'Xã']].dropna()

0        01677642406.0
50       01697685880.0
52        0968532997.0
54        0964338169.0
57        0968943324.0
58       01666172542.0
70        0987301586.0
74       01669528366.0
79        0981798697.0
81       01688972145.0
91       01682601885.0
94       01683973343.0
98       01689217697.0
100       0967982180.0
106       0975594243.0
107      01245259868.0
109       0946086346.0
111       0945312459.0
114       0973956639.0
122     016939355465.0
146      01663965255.0
207      01655515792.0
208       0912600256.0
215       0915326817.0
216      01662395340.0
217       0961503688.0
376      01629759761.0
378       0979746654.0
379       0966541150.0
381       0985017338.0
             ...
1310     01697223706.0
1311      0974635433.0
1319      0966665358.0
1321      0965625875.0
1328      0912003091.0
1332      0917626519.0
1337      0989645848.0
1338      0989071325.0
1340     01685376816.0
1347      0946851973.0
1354      0901234313.0
1355      0972729227.0
1363      0989457871.0
1367     01692134494.0
1376     01692539035.0
1380     01666000495.0
1383      0986842552.0
1385     01683525279.0
1386     01663205932.0
1393     01277012637.0
1396     01656080087.0
1403      0969569615.0
1410     01694586123.0
1413      0972458710.0
1419      0984266598.0
1420     01685762813.0
1424     01663194371.0
1431      0971410171.0
1438     01668401646.0
1440      0988071356.0
Name: SĐT, Length: 198, dtype: object